fix bugs in cut generator; clean up instance load
coin-or/MibS pull request #92
Opened 2022-01-18 20:47 UTC by yuxies

MibSCutGenerator:

1. generalNoGoodCut: condition check of SL-MILP, change from true to false;
2. benders interdiction cut: change a condition check and the initial value of valL;

MibSModel:

1. loadProblemData: remove an unused variable and redundant lines;
2. instanceStructure: add another condition check when assigning coefficient column signs; fix a bug when binary search rowIndex; fix typos and remove a redundant check when printing cut information.

2022-01-18 20:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/coin-or/MibS?pullRequest=92) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/coin-or/MibS?pullRequest=92) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/coin-or/MibS?pullRequest=92) it.</sub>

2022-01-28 19:52 UTC, tkralphs commented on src/MibSModel.cpp
> -      if (intCosts){
I lost the thread of why this if is not needed. Right now, it looks to me as though it is needed.

2022-01-28 19:54 UTC, tkralphs commented on src/MibSModel.cpp
> -         for(i = 0; i < auxULRows; i++){
I see why this is not needed because `auxULRows` should be zero when intCosts is 0, but the same logic doesn't apply to the above one.

2022-01-28 20:04 UTC, tkralphs commented on src/MibSModel.cpp
> +         } else if (!upperRow) {
This seems correct, but to make the logic match more obviously, I guess we could instead do
```
         } else {
            if (!upperRow) {
               ...
            }
         }
```
It would be even more clear if we had `lowerRow` instead of `upperRow` and we swap the order so that we have
```
         if (mult * matElements[j] < -etol_){
            if (lowerRow){
               ...
            } else {
               ...
            }
         } else {
            if (lowerRow){
               ...
            }
         }
```
Does it make sense?

2022-01-28 20:22 UTC, tkralphs commented on src/MibSCutGenerator.cpp
> +      valL = 0;
This change definitely does not seem right to me. Can you explain? It doesn't match what is in the paper. It will effectively end up with `-d^2 y <= d^2 y^*` instead of `-d^2 y <= d^2 y^*`

2022-01-28 20:27 UTC, tkralphs requested changes
I made some comments, could you address them and make the changes? You had also questioned some things in `instanceStructure()` that seemed like they should not be there. For example, around line 3175, `newRowSense` is being set, but nothing should really be set oin this function, it's just to analyze structure.

2022-01-31 10:02 UTC, yuxies commented on src/MibSModel.cpp
> -      if (intCosts){
Yes, since if not `intCosts`, then `auxULRows` is zero, and the fill function would not fill the bound. But I agree, keeping the condition can also remind about the dependency.

2022-01-31 10:03 UTC, yuxies commented on src/MibSModel.cpp
> -         for(i = 0; i < auxULRows; i++){
We can also keep this if it makes the logic clear, like the above one.

2022-01-31 10:09 UTC, yuxies commented on src/MibSModel.cpp
> +         } else if (!upperRow) {
> This seems correct, but to make the logic match more obviously, I guess we could instead do
> 
> ```
>          } else {
>             if (!upperRow) {
>                ...
>             }
>          }
> ```
Yes makes sense.

> It would be even more clear if we had `lowerRow` instead of `upperRow` and we swap the order so that we have
> 

We currently don't have the variable `lowerRow`, and  `upperRow` was a result of a binary search. I feel that adding a new variable here just for a condition check may bring redundancy.

2022-01-31 10:17 UTC, yuxies commented on src/MibSCutGenerator.cpp
> +      valL = 0;
Oh I think the variable is used to help load the coefficients of the term $\sum d^2_i y_i$ (at L5641), so it needs to be set to `0` at the beginning.

2022-01-31 13:30 UTC, tkralphs commented on src/MibSModel.cpp
> +         } else if (!upperRow) {
Yes, but if you use `lowerRow`, you don't need `upperRow` (they are complements of each other). The number of variables stays the same.  So can you make this change?

2022-01-31 13:31 UTC, tkralphs commented on src/MibSModel.cpp
> -      if (intCosts){
OK, yes, let's just keep it.

2022-01-31 13:31 UTC, tkralphs commented on src/MibSModel.cpp
> -         for(i = 0; i < auxULRows; i++){
Yes, let's just keep it, why not.

2022-01-31 13:33 UTC, tkralphs commented on src/MibSCutGenerator.cpp
> +      valL = 0;
It needs to be set to _something_ for sure, but 0 is wrong, as far as I can see. You didn't really explain _why_ you think it needs to be set to zero.

2022-01-31 13:39 UTC, tkralphs commented on src/MibSCutGenerator.cpp
> +      valL = 0;
We should probably just delete the line 5641 below (and the enclosing `else if` block), since it only reduces the coefficients, which technically weakens the cut (it is a `<=`). I think my logic was that the corresponding variables would never be nonzero anyway, but it doesn't harm anything to give them nonzero coefficients.

2022-01-31 21:49 UTC, yuxies commented on src/MibSModel.cpp
> +         } else if (!upperRow) {
okay I can do that... but just want to say that at L3260 `upperRow` was probably designed to match `upperCol`, and the change of variable will also affect L3266, L3337, and L3339.

2022-01-31 21:59 UTC, yuxies commented on src/MibSCutGenerator.cpp
> +      valL = 0;
I see. I forgot there is another term `d^2y` and only considered the conditioned summation. I will revert it back.

2022-01-31 22:46 UTC, tkralphs commented on src/MibSCutGenerator.cpp
> +      valL = 0;
OK, these are only suggestions, change as you see fit.

2022-02-01 20:40 UTC, tkralphs commented on src/MibSModel.cpp
> +   bool lowerRow, upperCol;
I was expecting you to also change `upperCol` to `lowerCol` for consistency :).

2022-02-09 16:48 UTC, tkralphs requested changes

2022-02-09 16:48 UTC, tkralphs commented on src/MibSModel.cpp
> +   instanceStructure(newMatrix, conLB, conUB, origRowSense_);
We don't really need to pass data members as function arguments, we can just directly access the data member in the called function. Looking at this, all the arguments are really data that should be stored in the class, so this function really shouldn't have any arguments. If you think about it, it wouldn't make sense to analyze data that wasn't actually stored in the class somewhere. So let's just make it so this function has no arguments.

2022-02-09 16:48 UTC, tkralphs commented on src/MibSModel.cpp
> +                             const char *newRowSense)
We can just change `newRowSense` to `rowSense` here (and throughout the function). The `new` part doesn't make sense out of context (all of this variable naming using `new` is not very intuitive and should ideally be changed, but we can tackle stuff like that later or just do it in version 2).

2022-02-09 20:32 UTC, yuxies commented on src/MibSModel.cpp
> +   instanceStructure(newMatrix, conLB, conUB, origRowSense_);
I can remove rowSense, but `newMatrix`, `conLB`, and `conUB` are initialized locally in `loadProblemData`, so unless I add this to `initialize()`, these arguments are still needed for data access.

2022-02-20 21:54 UTC, closed without merging